---
title: "Cleaning RITA Filight Data"
author: "ParisG"
date: "April 5, 2016"
output: html_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library('ggplot2')
library('dplyr')
library('gridExtra')
library('XLConnect')
library('sp')
library('RColorBrewer')
library('reshape')
library('ggthemes')
library('reshape2')
library('scales')
library('stats')
```

```{r,echo=FALSE, message=FALSE, warning=FALSE}
setwd("/Users/GEP/Documents/OneDrive/Academic/Udacity/Data_Vis_Code_Files/US Flights Visualization/data"
      
df <- read.csv('401340571_12016_2229_airline_delay_causes.csv', header=TRUE)
months <- c('Jan','Feb','Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep','Oct',
              'Nov', 'Dec')
str(df)
summary(df)
head(df)

df$date <- as.Date(paste(df$year, df$X.month, 1, sep='-'), format="%Y-%m-%d")
summary(df$date)

nrow(table(df$carrier))

# make a new summary table
ef <- df %>%
  group_by(date, year, carrier_name) %>%
  summarize(arrivals = sum(arr_flights),
            delayed = sum(arr_del15),
            cancelled = sum(arr_cancelled),
            diverted = sum(arr_diverted)) %>%
  transform(on_time = 1 - delayed/arrivals)

# stash NA values
ef <- ef[complete.cases(ef),]
ggplot(data = ef,
       aes(x = date, y = on_time)) +
  geom_line(aes(color = carrier_name))
```
